; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=instrumentor -instrumentor-read-config-file=%S/just_calls_config.json -S | FileCheck %s

target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

define ptr @bar(i1 %c) {
; CHECK-LABEL: define ptr @bar(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[B:%.*]] = alloca i32, i32 5, align 4
; CHECK-NEXT:    [[TMP0:%.*]] = call ptr @__just_calls_post_alloca(ptr [[B]], i64 20, i64 4)
; CHECK-NEXT:    [[TMP1:%.*]] = call ptr @__just_calls_post_alloca(ptr [[A]], i64 4, i64 4)
; CHECK-NEXT:    [[S:%.*]] = select i1 [[C]], ptr [[TMP1]], ptr [[TMP0]]
; CHECK-NEXT:    ret ptr [[S]]
;
entry:
  %a = alloca i32
  %b = alloca i32, i32 5
  %s = select i1 %c, ptr %a, ptr %b
  ret ptr %s
}
